package org.transparencia.gov2go.model.constantes;

public enum TipoOcorrencia {
	ILUMINACAO_PUBLICA,
	SINAL_TRANSITO,
	BURACO_VIAS,
	DENGUE,
	PODA_RETIRADA_ARVORES,
	BUEIROS,
	ESTACIONAMENTO_IRREGULAR,
	OCUPACAO_IRREGULAR,
	REMOCAO_ENTULHOS,
	CONTROLE_ROEDORES,
	LIMPEZA_URBANA,
	ESGOTO, 
	OUTROS;
}
